# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant file for provisioning minikube cluster
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
  
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    
    
  
    config.vm.define "kube1" do |minikube|
      minikube.vm.box = "centos/8"
      minikube.vm.network "private_network", ip: "192.168.33.1"
      minikube.vm.hostname = "minicluster"
      minikube.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
      end
      minikube.vm.provision "shell", path: "minikube_setup.sh"
      end
  end
    
    
   